main: com.hourglassprograms.dungeoncraft.Main
name: DungeonCraft
version: 0.0.5
author: Hourglass Programs
api-version: 1.15
commands:
  create-dungeon:
    description: "Use this to create a new dungeon"
    permission: dungeoncraft.create
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> <dungeon name>"
  create-arena:
    description: "Use this to create a new arena from your current position used for <dungeon name>"
    permission: dungeoncraft.create-arena
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> <dungeon name>"
  start-dungeon:
    description: "Use this to start a dungeon"
    permission: dungeoncraft.start-dungeon
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> <dungeon name> <difficulty>"
  dc-reload:
    description: "Use this to reload config"
    permission: dungeoncraft.reload
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command>"
