main: com.hourglassprograms.dungeoncraft.Main
name: DungeonCraft
version: 0.0.2
author: Hourglass Programs
api-version: 1.15
commands:
  dungeoncraft create:
    description: "Use this to create a new dungeon"
    permission: dungeoncraft.create
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> <name>"
