main: com.hourglassprograms.dungeoncraft.Main
name: DungeonCraft
version: 0.0.1
author: Hourglass Programs
api-version: 1.15
commands:
  hello:
    description: "Use this to get the port or auth key or to link with the Discraft Server"
    permission: discraft.use
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> (port <new port>:auth <authkey>:link)"
