main: com.hourglassprograms.dungeoncraft.Main
name: DungeonCraft
version: 0.0.14
author: Hourglass Programs
api-version: 1.15
commands:
  create-dungeon:
    description: "Use this to create a new dungeon"
    permission: dungeoncraft.dungeon.create
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> <dungeon name>  [wave count]"
  create-arena:
    description: "Use this to create a new arena from your current position used for <dungeon name>"
    permission: dungeoncraft.arenas.create
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> <dungeon name> [spawn radius]"
  arenas:
    description: "Use this to list all the arenas"
    permission: dungeoncraft.arenas.list
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command>"
  start-dungeon:
    description: "Use this to start a dungeon"
    permission: dungeoncraft.start
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> <dungeon name> <difficulty> [player name]"
  dc-reload:
    description: "Use this to reload config"
    permission: dungeoncraft.reload
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command>"
  party:
    description: "Command to manipulate the parties"
    permission: dungeoncraft.party
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> [list:create:invite <name>:accept:leave]"
